name: Sitemap Ping

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed
  workflow_dispatch:

jobs:
  ping:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Ping Google
        run: |
          curl -s "https://www.google.com/ping?sitemap=https://bochi-it-note.com/sitemap-index.xml" || true
      - name: Ping Bing
        run: |
          curl -s "https://www.bing.com/ping?sitemap=https://bochi-it-note.com/sitemap-index.xml" || true


